# Generated by Django 4.1.3 on 2023-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=6000)),
                ('location', models.CharField(default='Mumbai', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Careers',
            },
        ),
    ]
