# Generated by Django 4.1.3 on 2023-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hblogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('author', models.CharField(default='Pacify Medical Technologies ', max_length=100, null=True)),
                ('blogs', models.TextField(max_length=6000, null=True, verbose_name='Blogs')),
            ],
            options={
                'verbose_name_plural': 'Homeblogs',
            },
        ),
        migrations.CreateModel(
            name='HImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='Add image url here', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'HomeImages',
            },
        ),
        migrations.CreateModel(
            name='HLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='Add image url here', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'HomeLogo',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(default=' ', max_length=100, null=True)),
                ('news', models.TextField(max_length=6000, null=True, verbose_name='News')),
            ],
            options={
                'verbose_name_plural': 'HomeNews',
            },
        ),
    ]
