# Generated by Django 4.1.3 on 2023-07-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='Add image url here', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'AwardsImages',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(max_length=500, null=True, verbose_name='Details')),
            ],
            options={
                'verbose_name_plural': 'Awards',
            },
        ),
    ]
